#!/usr/bin/env python3
import sys
from analyzer import Analyzer
from helpers import get_user_timeline
from termcolor import colored
import os
def main():
    if len(sys.argv) == 2:
        # absolute paths to lists
        positives = os.path.join(sys.path[0], "positive-words.txt")
        negatives = os.path.join(sys.path[0], "negative-words.txt")
    
        # instantiate analyzer
        analyzer = Analyzer(positives, negatives)
        tweets = get_user_timeline(sys.argv[1].strip('@'),50)
        if tweets == None:
            print("Usage: ./tweets @screen_name")
            exit(1)
        else:
            #Check Score
            for tweet in tweets:
                score = analyzer.analyze(tweet)
                if score > 0.0:
                    print(colored(str(score)+' '+tweet, "green"))
                elif score < 0.0:
                    print(colored(str(score)+' '+tweet, "red"))
                else:
                    print(colored(str(score)+' '+tweet, "yellow"))
    else: 
        print("Usage: ./tweets @screen_name")
        exit(1)
    
    
    
    
    
if __name__ == "__main__":
    main()
            
